arr_arr = [
    ['How much do the workers care about using safety equipment such as helmets, safety shoes, etc.?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much do the workers pay attention to management orders about safety?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much is it possible to observe safety rules on the site?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['Will management fine the workers who do not follow safety rules?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['Will the workers get the reward if they follow safety rules on your site?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['How much does the management care about the safety welfare of the workers?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much does the management use safety equipment on the site?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much does the management provide the site`s safety equipment for the workers?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['Has improved the safety condition on the site been a management concern?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['Are there any boards, danger signs, danger bars, etc, on your site for use in emergencies?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['How much do the workers know about how to use safety equipment on the site?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much do the workers know about how to act in emergencies?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much awareness do the workers have about the safety hazards?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much awareness do the workers have about their responsibilities for safety on the site?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['Do the site`s workers have a technical skills card?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['Are safety courses held on the site for workers?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['Are safety inspections carried out by the management on the site?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['How much do the safety inspections check on your site if it is done?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['Do the managers warn the offenders of unsafe behaviors that are observed on the site?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['How much do engineers and site management know the safety rules?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['How much do the site`s workers know the safety rules?',[{'label':'Very low','vall':'1'},{'label':'Low','vall':'3'},{'label':'Moderate','vall':'5'},{'label':'High','vall':'7'},{'label':'Very high','vall':'9'}]],
    ['Are safety instructions and rules laid down on the site?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
    ['Is there an HSE engineer or safety personnel on your site?',[{'label':'Yes','vall':'9'},{'label':'No','vall':'1'}]],
]